services:
  front:
    build: ./fire-ui
    environment:
      REACT_APP_API_FIRE_OPT: http://localhost:41983

  opt:
    build: ./fire-opt
    environment:
      API_PORT: 80
      API_FIRE_ROUTE: http://route/travel
    ports:
      - 41983:80

  route:
    build: ./fire-route
    environment:
      API_PORT: 80
    ports:
      - 41982:80
